[[section-introduction-and-goals]]
== Introduction and Goals

The aim of this system is to create an application that facilitates meetings between friends using new technologies. It uses the mobile phone location of the users willing to activate it and allows them to connect other users, their friends. 

The application will allow to notify a user when there is some friend nearby so they can get in touch.
The user will be able to be notified when one of his friends is nearby, so they can get in touch.

The system will be decentralized, compatible with a SOLID project and it will not store users' personal information in a centralized way, but will ask for permission to get to that information using users' pods.

The system will only store locations and timestamps in which those locations happen.

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****


=== Requirements Overview

[role="arc42help"]
****

.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

The requirements for the Radarin application are the following 

* Users should be able to know the ubications of other users who allow it. 
* Users would be able to accept others as their friends in order to share information. 
* Users would have the option to share their information with friends. 
* Users' data should be stored in the users' PODs.
* Notifications on demand would be available.


=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

[options="header",cols="1,2,2"]
|===
|Priority|Quality goal|Motivations
|P01 |Decentralization | Avoids security issues. We reach this goal by storing information in SOLID pods. 
|P02| Usability | The application must be understandable and easy to use for users with different levels of IT knowledge.
|P03| Performance | The application must load each web page in less than 5 seconds.
|P04| Clean code | Code should be easy to understand and easy to change.
|P05| Testability | The system should be prepared for testing puposes.
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Description|Expectations
|_Professor_ |In charge of supervising and evaluating the project | Surpervises student´s work and provides guidance
|_Users_ | The people who will use the application | They would expect a usable producto. An application than meets the expected requierements
| _Team_ | The software developers of this application | They expect to learn about SOLID and the new proposed frameworks and technologies in order to display the best product possible. 
| _Project sponsor_ | Inrupt/Empathy | They encourage us to participate in the SOLID challenge. 
|===
