[[section-runtime-view]]
== Runtime View

=== Login

For the login, the app shows the login view which asks the user for their Solid Identity Provider of choice.
Then the app does a login request to the REST API server, which redirects the user to the identity provider
which handles the authentication.
Once the user successfully logs in, the identity provider gives the server the session information needed
to interact with the user Pod, and the server sends the session ID to the web app, which can be used to
identify the session in later REST API requests. Lastly, the web app shows the main view.

[plantuml,"Sequence diagram - Login",png]
----
actor User as U
participant "Web App/ Mobile app" as W
participant "REST API Server" as R
participant "Solid Identity Provider" as P

activate W
W -> W: Show Login View
U -> W: Chooses Solid Identity Provider
W -> R: Requests login
deactivate W
activate R
R -> P: Redirects to the provider login form
deactivate R
activate P
P --> U: Asks for credentials
activate U
U -> P: Logs in
deactivate U
P --> R: Provides session information
deactivate P
activate R
R --> W: Provides session ID
activate W
W -> W: Show Main View
----

This diagram also applies to the mobile app. 

=== Nearby friends

Whenever a user updates his last location with a new one, the restapi will update it in his POD and the proceed to iterate throught this user's 
friend's list checking their most recent uploaded location and computing the distance between the user and all his friends. If this distance is below a 
threshold which for the moment is a constant set to 5 km, it is considered to be close to the user and it is added to an array of nearby friends. 

In order for the user's nearby friends to be notified of his new near location, a Websockets server was implemented in the restapi and a Websockets 
client endpoint was implemented in the mobileapp. The WebSocket protocol provides a way to exchange data between browser and server via a persistent 
connection. The data can be passed in both directions as “packets”, without breaking the connection and additional HTTP-requests.

So the array of nearby friends which is stored in the restapi is iterated through and for each friend, a notification is sent via the connection established 
between his mobileapp client endpoint and the restapi server and it pops up in the mobile application letting this user know that his friend is now close to him.

[plantuml,"Sequence diagram - Nearby friends",png]
----
actor "User" as U
participant "Mobile App" as M
database "User Pod" as UPod
database "Friend Pod" as FPod

U -> M: Allows "nearby friends" notifications
activate M
loop periodically
    ...
    M -> UPod: Requests friend list
    activate UPod
    return friend list
    loop for each friend
        M -> FPod: Requests latest location
        activate FPod
        return latest location
        opt If latest location is nearby
            M -> M: Notify user
        end
    end
end
----
