[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Login

For the login, the app asks the user for their Solid Identity Provider of choice.
Then the user is redirected to the identity provider which handles the authentication.
Once the user successfully logs in, the identity provider gives the web app the
session information needed to interact with the user Pod, and redirects back to the app.

[plantuml,"Sequence diagram - Login",png]
----
actor User as U
participant "Web App" as W
participant "Solid Identity Provider" as P
U -> W: Chooses Solid Identity Provider
activate W
W -> P: Redirect to the provider login form
deactivate W
activate P
P --> U: Asks for credentials
activate U
U -> P: Logs in
deactivate U
P --> W: Provides session information
activate W
P -> W: Redirects to the web app
deactivate P
----
=== <Runtime Scenario 2>

=== ...

=== <Runtime Scenario n>
