[[section-runtime-view]]
== Runtime View

=== Login

For the login, the app shows the login view which asks the user for their Solid Identity Provider of choice.
Then the app does a login request to the REST API server, which redirects the user to the identity provider
which handles the authentication.
Once the user successfully logs in, the identity provider gives the server the session information needed
to interact with the user Pod, and the server sends the session ID to the web app, which can be used to
identify the session in later REST API requests. Lastly, the web app shows the main view.

[plantuml,"Sequence diagram - Login",png]
----
actor User as U
participant "Web App/ Mobile app" as W
participant "REST API Server" as R
participant "Solid Identity Provider" as P

activate W
W -> W: Show Login View
U -> W: Chooses Solid Identity Provider
W -> R: Requests login
deactivate W
activate R
R -> P: Redirects to the provider login form
deactivate R
activate P
P --> U: Asks for credentials
activate U
U -> P: Logs in
deactivate U
P --> R: Provides session information
deactivate P
activate R
R --> W: Provides session ID
activate W
W -> W: Show Main View
----

This diagram also applies to the mobile app. 
=== Nearby friends

If the user allows the "nearby friends" notifications, a check will be done periodically which accesses
their friends list to get their latest location from their Pods. If any friend location is nearby enough,
a notification will be sent to the user. How often the check is done and which distance is considered
nearby can be configured by the user.

[plantuml,"Sequence diagram - Nearby friends",png]
----
actor "User" as U
participant "Mobile App" as M
database "User Pod" as UPod
database "Friend Pod" as FPod

U -> M: Allows "nearby friends" notifications
activate M
loop periodically
    ...
    M -> UPod: Requests friend list
    activate UPod
    return friend list
    loop for each friend
        M -> FPod: Requests latest location
        activate FPod
        return latest location
        opt If latest location is nearby
            M -> M: Notify user
        end
    end
end
----
