[[section-design-decisions]]
== Design 

.*Constraints*
* Use SOLID as a technology to make the project decentralized. Supports the librarie React.
* Use React to desing the user interface.

.*Problems*
* Decision making related to architecture, model of domian... etc.
* Lack of experience of the team regarding the technologies needed to the project.

.*Decisions*
* Use JavaScript not just because it is a constraint but because its support of SOLID makes the development of the project much more fluid
* Incorporate the react framework because it is a great and extended way to create graphical user interfaces based in JavaScript.
* Research the new technologies and features that the team is not used to deal with in order to get familiarized with them.


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
