[[section-technical-risks]]
== Risks and Technical Debts


[options="header"]
|===
| Priority         | Risk  | Consequence | Possible Solution
| 1     | New technologies |  The project requires the usage of a new technologies that are completely new for the developers. No one has ever worked with SOLID or React and some others never used javascript | Initial period of investigation and learning of the needed tools, good division of the tasks

| 2     | Team organization | Working with other people in a team always leads to some problems, specially when no member of the team has ever worked with the others | Frequent meetings allowing a fluent communication, good organization of the tasks.
|===


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****
