name: CI for radarin

on:
  push:
    branches: [ master ]

jobs:
  build-test-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: codecov/codecov-action@v1
  build-test-restapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: restapi
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - run: npm ci
    - run: npm test
    - uses: codecov/codecov-action@v1
  build-test-mobileapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobileapp
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - run: npm pack ../restapi/client && npm install restapi-client-0.1.0.tgz # need to install it again because the integrity checksum in package-lock.json may be different due to different OS in CI server and local dev machines
    - run: npm ci
    - run: npm test
    - uses: codecov/codecov-action@v1
  e2e-tests:
    needs: [build-test-webapp, build-test-restapi]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - run: | # add subdomains from the Solid server users
        sudo echo "127.0.0.1 user1.localhost" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 user2.localhost" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 user3.localhost" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 user4.localhost" | sudo tee -a /etc/hosts
    - run: npm --prefix webapp install
    - run: npm --prefix restapi install
    - run: npm --prefix webapp run test:e2e
  deploy-mobileapp:
    needs: [build-test-mobileapp]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobileapp
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - run: npm pack ../restapi/client && npm install restapi-client-0.1.0.tgz # need to install it again because the integrity checksum in package-lock.json may be different due to different OS in CI server and local dev machines
    - run: npm ci
    - run: cd android && ./gradlew assembleRelease
    - run: mv android/app/build/outputs/apk/release/app-release.apk radarinen2a-mobileapp.apk
    - name: Upload mobileapp APK
      uses: actions/upload-artifact@v2
      with:
        name: radarinen2a-mobileapp
        path: radarinen2a-mobileapp.apk
  deploy-webapp:
    needs: [deploy-mobileapp, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./restapi/client ./webapp/restapi-client # the Dockerfile cannot access files outside the `webapp` directory, so copy this local dependency inside
      - name: Download mobileapp APK
        uses: actions/download-artifact@v2
        with:
          name: radarinen2a-mobileapp
          path: webapp/public
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "radarinen2awebapp" #Must be unique in Heroku
          heroku_email: "asw2021en2a@gmail.com"
          usedocker: true
          appdir: "webapp"
          docker_build_args: |
            API_URI
        env:
          API_URI: "https://radarinen2arestapi.herokuapp.com/api"
  deploy-restapi:
    needs: [e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "radarinen2arestapi" #Must be unique in Heroku
          heroku_email: "asw2021en2a@gmail.com"
          usedocker: true
          appdir: "restapi"
          docker_build_args: |
            MONGO_URI
            API_URI
        env:
          MONGO_URI: ${{secrets.MONGO_URI}}
          API_URI: "https://radarinen2arestapi.herokuapp.com/api"

